#!/usr/bin/env node
//
// generate-types.mjs — emits dist/index.d.ts from the built bundle.
//
//   node scripts/generate-types.mjs
//
// Why generated rather than hand-written
// -------------------------------------
// The package exports 65 symbols and the classes carry hundreds of chainable
// methods between them. A hand-written .d.ts would be wrong within a release,
// and a .d.ts that lies is worse than none: the editor and the compiler both
// stop being able to catch anything. Reading the real prototypes keeps it
// honest by construction.
//
// The bundle is a browser build and touches `window` at import time, so this
// installs a minimal DOM stub first. That is also why `require("nodality")`
// throws in bare Node — worth knowing if you ever want to unit-test against it.
//
// What this buys an agent
// -----------------------
// Autocomplete over the real API, and — the specific reason this exists — the
// `text` vs `value` trap becomes a compile error instead of an element that
// renders blank with no explanation.
//

import { writeFileSync, mkdirSync } from "fs";
import { createRequire } from "module";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const require = createRequire(import.meta.url);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// --- minimal DOM so the browser bundle can be imported at all -------------
const noop = () => {};
const el = () => ({
  style: {}, children: [], classList: { add: noop, remove: noop, contains: () => false },
  appendChild: noop, setAttribute: noop, addEventListener: noop, querySelectorAll: () => [],
});
globalThis.window = globalThis;
globalThis.document = {
  createElement: el, createTextNode: el, body: el(), head: el(),
  querySelector: () => null, querySelectorAll: () => [], addEventListener: noop,
};
// Node 22 defines `navigator` as a getter-only global, so a plain assignment
// throws. Only define it when it is genuinely absent.
if (!globalThis.navigator) {
  Object.defineProperty(globalThis, "navigator", {
    value: { userAgent: "node" }, configurable: true, writable: true,
  });
}
globalThis.location = { href: "http://localhost/", origin: "http://localhost" };

const mod = require(resolve(ROOT, "dist/index.cjs.js"));

/** Public instance methods of a class, excluding the constructor. */
function methodsOf(fn) {
  if (typeof fn !== "function" || !fn.prototype) return [];
  return Object.getOwnPropertyNames(fn.prototype)
    .filter((n) => n !== "constructor" && !n.startsWith("_"))
    .filter((n) => {
      const d = Object.getOwnPropertyDescriptor(fn.prototype, n);
      return d && typeof d.value === "function";
    })
    .sort();
}

const names = Object.keys(mod).sort();
const classes = names.filter((n) => typeof mod[n] === "function" && mod[n].prototype);
const funcs = names.filter((n) => typeof mod[n] === "function" && !classes.includes(n));

let out = `// Generated by scripts/generate-types.mjs — do not edit by hand.
//
// Nodality ${require(resolve(ROOT, "package.json")).version}
//
// You describe a page as two plain arrays and hand them to a Designer:
//
//     import { Des } from "nodality";
//
//     const elements = [{ type: "h1", text: "Hello" }];
//     const nodes    = [{ op: "blast" }];
//
//     new Des().nodes(nodes).add(elements).set({ mount: "#mount" });
//

/**
 * One element to render.
 *
 * The content property is \`text\`. It is NOT \`value\` — \`value\` means a
 * keyframe value or the name of an animated property elsewhere in the API, and
 * an element given \`value\` renders blank with no error.
 */
export interface ElementSpec {
  /** Tag name or Nodality element type, e.g. "h1", "text", "image". */
  type: string;
  /** The element's text content. */
  text?: string;
  /** Identifier, used by nodes to target this element. */
  name?: string;
  id?: string;
  /**
   * @deprecated Elements take \`text\`, not \`value\`.
   *
   * Typed as \`never\` on purpose. The index signature below has to allow
   * arbitrary options — element classes accept hundreds between them — which
   * would otherwise let \`value\` through silently, and an element given
   * \`value\` renders blank with no error at all. Declaring it \`never\` makes
   * exactly that one mistake a compile error while leaving every real option
   * alone. Five documentation pages had it wrong; this is what stops the sixth.
   */
  value?: never;
  /** Any other option the matching element class accepts. */
  [option: string]: unknown;
}

/** One node: something applied to elements, identified by \`op\`. */
export interface NodeSpec {
  /** The operation, e.g. "blast", "shadow", "gradient", "filter". */
  op: string;
  /** Which element this applies to, by \`name\`. */
  target?: string;
  [option: string]: unknown;
}

export interface DesOptions {
  /** CSS selector the tree is mounted into. */
  mount?: string;
  [option: string]: unknown;
}

`;

for (const name of classes) {
  const ms = methodsOf(mod[name]);
  out += `/** ${name} — ${ms.length} method${ms.length === 1 ? "" : "s"}. */\n`;
  out += `export class ${name} {\n`;
  out += `  constructor(...args: any[]);\n`;
  for (const m of ms) out += `  ${m}(...args: any[]): any;\n`;
  out += `}\n\n`;
}

for (const name of funcs) {
  out += `export function ${name}(...args: any[]): any;\n`;
}

out += `\ndeclare module "nodality/ssg" { export function prerender(...args: any[]): any; }\n`;
out += `declare module "nodality/ssg-site" { export function prerenderSite(...args: any[]): any; }\n`;
out += `declare module "nodality/seo" { export function applySeoMeta(...args: any[]): any; }\n`;
out += `declare module "nodality/data" { export function loadJson(...args: any[]): any; }\n`;

// nodality/morph — the pure core of the morph op. Declared by hand rather
// than read off the bundle like the classes above, because morph.js is
// deliberately NOT in the bundle: it must import in bare Node (no window),
// which is the whole point of the subpath. M4 replaces the loose token
// types below with unions generated from the registry, so a misspelled
// token becomes a compile error instead of a runtime throw.
out += `
declare module "nodality/presets" {
  /** A raster node: \`{ op, ...params }\`, plus \`by\` for a driver and \`masked\`/\`as\` for fields. */
  export interface RasterNode { op: string; by?: string; masked?: string | true; as?: string; [param: string]: unknown; }
  export const PRESETS: Record<string, { summary: string; live?: "enhanced" | "required"; nodes: RasterNode[] }>;
  /** Preset names, in declaration order. */
  export function presetNames(): string[];
  /** \`{ summary, live }\` — what a gallery badges from. Throws with a did-you-mean on an unknown name. */
  export function presetInfo(name: string): { summary: string; live?: "enhanced" | "required" };
  /** A preset's nodes as a fresh array; \`overrides\` is applied shallowly to every node. */
  export function preset(name: string, overrides?: Record<string, unknown>): RasterNode[];
  /** Concatenate presets into one chain, renaming each part's private fields so they cannot collide. */
  export function compose(...parts: (string | [string, Record<string, unknown>] | RasterNode[])[]): RasterNode[];
  /** Check ops, drivers and field references against the live vocabulary. Never throws. */
  export function validateChain(nodes: RasterNode[]): { ok: boolean; errors: string[] };
}

declare module "nodality/morph" {
  export interface MorphSpec { op: "morph"; target: string; seed?: number; [key: string]: unknown; }
  export interface MorphError { code: string; path: string; got: unknown; suggestions: string[]; valid: string[]; }
  export interface MorphReport { ok: boolean; errors: MorphError[]; }
  export interface MorphExpansion {
    elements: any[]; nodes: any[];
    slots: { id: string; kind: string }[];
    meta: { rootId: string; vars: Record<string, string | number>; tracks: any; slots: { id: string; kind: string }[] };
  }
  export interface MorphController {
    axis(name: string, v: number): MorphController;
    axes(map: Record<string, number>): MorphController;
    content(slotId: string, value: unknown): MorphController;
    dispose(): MorphController;
  }
  /** Validate a spec. Never throws — a malformed spec IS a report. */
  export function validate(spec: unknown): MorphReport;
  /** Expand a spec into ordinary (elements, nodes). Throws LayoutSpecError, which carries the report on \`err.report\`. */
  export function expand(spec: MorphSpec): MorphExpansion;
  /** The constraint solver. Returns exact sizes plus an integer rounding whose sum is exactly \`container\`. */
  export function allocate(container: number, tracks: any[]): { sizes: Record<string, number>; relaxed: string[]; rounded: Record<string, number> };
  /** Bind a mounted expansion to the DOM. The only DOM-touching export. */
  export function morphController(specOrMeta: MorphSpec | MorphExpansion["meta"], rootEl?: any): MorphController;
  export function mulberry32(seed: number): () => number;
  export const REGISTRY: any;
  export const AXES: any;
}
`;

mkdirSync(resolve(ROOT, "dist"), { recursive: true });
writeFileSync(resolve(ROOT, "dist/index.d.ts"), out);

const methodTotal = classes.reduce((n, c) => n + methodsOf(mod[c]).length, 0);
console.log(`  dist/index.d.ts written`);
console.log(`    ${classes.length} classes, ${funcs.length} functions, ${methodTotal} methods`);
